name: CI

on: [push, pull_request]

env:
  rust-toolchain: nightly-2025-05-20

jobs:
  clippy:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          arch: [x86_64, riscv64, aarch64, loongarch64]
          rust-toolchain: [nightly, nightly-2025-05-20]
      env:
        RUSTUP_TOOLCHAIN: ${{ matrix.rust-toolchain }}
      steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rust-src, clippy, rustfmt
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat, loongarch64-unknown-none-softfloat
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-bin-cache
          cache-targets: false
      - name: Check rust version
        run: rustc --version --verbose
      - name: Check code format
        if: ${{ matrix.arch == 'x86_64' }}
        continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
        run: cargo fmt --all -- --check
      - name: Clippy for the default target
        if: ${{ matrix.arch == 'x86_64' }}
        continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
        run: make clippy
      - name: Clippy for ${{ matrix.arch }}
        continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
        run: make clippy ARCH=${{ matrix.arch }}

  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly-2025-05-20, nightly]
        targets: [x86_64-unknown-linux-gnu, 
                  x86_64-unknown-none, 
                  riscv64gc-unknown-none-elf, 
                  aarch64-unknown-none-softfloat,
                  loongarch64-unknown-none-softfloat]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: ${{ matrix.targets }}
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: cargo clippy --target ${{ matrix.targets }} --all-features -- -A clippy::new_without_default
    - name: Build
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: cargo build --target ${{ matrix.targets }} --all-features
    - name: Unit test
      if: ${{ matrix.targets == 'x86_64-unknown-linux-gnu' }}
      continue-on-error: ${{ matrix.rust-toolchain == 'nightly' }}
      run: cargo test --target ${{ matrix.targets }} -- --nocapture

  doc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust-toolchain }}
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: cargo-bin-cache
        cache-targets: false
    - name: Build docs
      continue-on-error: ${{ github.ref != env.default-branch && github.event_name != 'pull_request' }}
      run: make doc_check_missing
    - name: Deploy to Github Pages
      if: ${{ github.ref == env.default-branch }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: true
        branch: gh-pages
        folder: target/doc
        